#import libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
lst = [0,1,2]
nd = np.array(lst)
print(lst)
print(type(lst))
print(nd)
print(type(nd))

[0, 1, 2]
<class 'list'>
[0 1 2]
<class 'numpy.ndarray'>


In [3]:
print(lst*2)
print(nd*2)

[0, 1, 2, 0, 1, 2]
[0 2 4]


##リスト*2は全要素を2回繰り返す。

##nd.array*2は、全要素を二倍する。

In [4]:
a = [0,1,2]
b = [3,4,5]
print(type(a))
print(a + b)
##print(a*b)は定義されない

<class 'list'>
[0, 1, 2, 3, 4, 5]


In [5]:
a = np.array([0,1,2])
b = np.array([3,4,5])
print(type(a))
print(a*b)
print(a+b)

<class 'numpy.ndarray'>
[ 0  4 10]
[3 5 7]


In [13]:
df = pd.DataFrame([[0,1,2],[3,4,5]], columns = ['c0','c1','c2'])
print(type(df))
print(df.shape)
display(df)
print(df)

<class 'pandas.core.frame.DataFrame'>
(2, 3)


c0  c1  c2
0   0   1   2
1   3   4   5

   c0  c1  c2
0   0   1   2
1   3   4   5


In [7]:
df2 = pd.DataFrame([[0,1,2],[3,4,5]], columns = ['c0','c1','c2'], index = ['r0','r1'])
display(df2)

c0  c1  c2
r0   0   1   2
r1   3   4   5

In [8]:
df3 = pd.DataFrame([[0,1,2],[3,4,5]])
display(df3)
df3.columns =  ['c0','c1','c2']
df3.index =  ['r0','r1']
display(df3)

0  1  2
0  0  1  2
1  3  4  5

c0  c1  c2
r0   0   1   2
r1   3   4   5

In [12]:
import numpy as np

# 2次元のndarrayを正しく作成する
df4 = np.array([[0, 1, 2], 
                 [3, 4, 5]])

# 配列を表示
print(df4)
print(type(df4))
display(df4)

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>


array([[0, 1, 2],
       [3, 4, 5]])